name: ci

on:
  push:
    branches: [ main , "2.0" ]
  pull_request:
    branches: "*"

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.15
        os:
          - ubuntu-latest

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: check out code into the Go module directory
        uses: actions/checkout@v2

      - name: check license header
        run: |
          git clone https://github.com/lsm-dev/license-header-checker.git && \
          cd license-header-checker && \
          make install && \
          cd .. && \
          license-header-checker -a -v -r -i vendor,license-header-checker header/license_header.txt . go && \
          [[ -z `git status -s` ]]

      - name: gofmt
        run: |
          go fmt ./... && git status && [[ -z `git status -s` ]]
          # diff -u <(echo -n) <(gofmt -d -s .)

      - name: test request struct
        #        run: go test -v request/...
        run: go test -v ./request

      - name: Post Coverage
        run: bash <(curl -s https://codecov.io/bash)