name: dingtalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.15
        os:
          - ubuntu-latest

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install imports-formatter
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          git clone https://github.com/dubbogo/tools.git
          cd tools/cmd/imports-formatter
          go install

#      - name: Install license-header-checker
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin
#          git clone https://github.com/lsm-dev/license-header-checker.git
#          cd license-header-checker
#          make install

#      - name: Check License Header
#        run: |
#          pwd
#          license-header-checker -v -a -r -i vendor,license-header-checker,tools ./header/license_header.txt . go
#          rm -rf license-header-checker
#          [[ -z `git status -s` ]]

      - name: Check improts
        run: |
          imports-formatter -path . -module github.com/zhaoyunxing92/dingtalk/v2 -bl false
          rm -rf tools
          [[ -z `git status -s` ]]

      - name: gofmt
        run: |
          go fmt ./... && && git status && [[ -z `git status -s` ]]
          # diff -u <(echo -n) <(gofmt -d -s .)

      - name: Test Request Struct
        #        run: go test -v request/...
        run: go test -v ./request -race -coverprofile=coverage.txt -covermode=atomic -v

      - name: Post Coverage
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}